### PR TITLE
misc cleanup and changes groupme-fetch and user-stats, add like information

### PR DESCRIPTION
**Pull request by czue**
there are a bunch of changes bundled together here from me working on this to suit it more to my needs.

it's basically backwards compatible though i changed the api slightly to make use of all the builtin argparse functionality.

won't be offended if you don't want to pull in these changes - but thought I would share them in case you think they're an improvement. :)

### CODE REVIEW

**Comment by cdzombak** [comment]
thanks @czue! I don't have time to look in detail this week (on vacation), but these changes look promising.

**Comment by czue** [comment]
:+1: thanks for the library was just what i was looking for!

**Comment by diego898** [comment]
These additions seem great!

**Comment by czue** [comment]
@diego898 thanks! I forgot to mention that I also added like data to the user stats and did a similar cleanup to it. i forgot that my pushes to my own fork would just update this PR in place.

@cdzombak let me know if you have any feedback

**Comment by cdzombak** [comment]
I'm not really using GroupMe any more, so I can't run this through its paces, but it looks like @czue and @diego898 have tried this, so ¯\\\_(ツ)\_/¯

**Comment by diego898** [comment]
@cdzombak full disclosure! I have *not* tried the changes out, jsut browsed the various commits and liked what I saw. I will be trying them out shortly now that they are on master and will report back! sorry for the confusion!

**Pull request merged**
